### ISSUE TITLE
256位

### ISSUE THREAD

**Issue by xfmaster** [hoylen/dart-crypt#2]
怎么生成256位的字符串

**Comment by hoylen** [comment]
```dart
import 'dart:math';

const String _charSet =
  '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';

final _rnd = new Random();

String randomBytes(int numBytes) {
  final bytes = <int>[];

  for (var x = 0; x < numBytes; x++) {
    bytes.add(_charSet.codeUnitAt(_rnd.nextInt(_charSet.length)));
  }

  return new String.fromCharCodes(bytes);
}

void main() {
  final s = randomBytes(256 ~/ 8);
  print(s);
}
```

Note: [Random](https://api.dartlang.org/stable/1.24.3/dart-math/Random-class.html) is not cryptographically strong. Use [Random.secure](https://api.dartlang.org/stable/1.24.3/dart-math/Random/Random.secure.html) if it is available.

**Comment by xfmaster** [comment]
谢谢，可能我没说清楚，我的意思是这个用RSA加密生成的是64位的 ，但我这里要256位的怎么做呢

**Comment by hoylen** [comment]
I don't know what you are looking for.

This package only uses SHA-256. It does not use RSA, because there is no support for RSA in the [Unix crypt](https://akkadia.org/drepper/SHA-crypt.txt) specification.
