### ISSUE TITLE
想要在node上解密生成的字符串应该怎么做

### ISSUE THREAD

**Issue by Allure-eve** [hoylen/dart-crypt#3]

**Comment by hoylen** [comment]
The whole point of crypt is that it cannot be decrypted.

To test if the entered password matches, calculate its crypt value (using the same seed and number of rounds) and test if the two crypt values are the same or not.

**Comment by Allure-eve** [comment]
多谢，我想我明白你的意思了。：)

**Comment by hoylen** [comment]
Use [match](https://pub.dev/documentation/crypt/latest/crypt/Crypt/match.html):

```dart
var c = new Crypt(r'$5$xYWYo0raYwLSchAd$na8cL1H.ESWtof6DNwraE6p8WI9DYObZ3irMe01Guk6');
var suppliedValue = 'p@ssw0rd';

if (c.match(suppliedValue)) {
  print('ok');
} else {
  throw ...
}
```
